spring:
  application:
    name: Future-Transitions

  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=future-vision;encrypt=false
    username: sa
    password: cya.khu1955
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 15MB

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect

  mail:
    host: smtp.gmail.com               # the type of email we send the email
    port: 587
    username: syambolazi@gmail.com    # my normal email
    password: sxmlqtkmfmkidkcd       # password from app password not my actual email password
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            trust: "*"     #to avoid certification check

    elasticsearch:
      uris: http://localhost:9200
      connection-timeout: 5s
      read-timeout: 5s

jwt:
  secret: JDDwnyo4Bt99yxC3Jh/dol6XN9hkaeoqzANPE2eDg3bEq83JSYoOpBDHVbvV5faD1FL+wcbczfsnegRynV+8tg==

file:
  upload-dir: uploads/

app:
  reset-password:
    url: https://yourfrontend.com/reset-password
